server {
  listen 8080;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  # cache largo para assets con hash en el nombre
  location /assets/ {
    expires 1y;
    add_header Cache-Control "public, immutable";
    try_files $uri =404;
  }

  # SPA: cualquier ruta no resuelta cae a index.html para que React Router maneje
  location / {
    try_files $uri $uri/ /index.html;
  }

  # health endpoint para healthcheck del compose
  location = /healthz {
    access_log off;
    return 200 "ok\n";
    add_header Content-Type text/plain;
  }
}
