server:
  port: 8084

spring:
  application:
    name: bff
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_JWK_URI:http://keycloak:8080/realms/innovatech/protocol/openid-connect/certs}

keycloak:
  admin:
    base-url: ${KEYCLOAK_ADMIN_URL:http://keycloak:8080}
    realm: ${KEYCLOAK_REALM:innovatech}
    admin-realm: ${KEYCLOAK_ADMIN_REALM:master}
    client-id: ${KEYCLOAK_ADMIN_CLIENT_ID:admin-cli}
    username: ${KEYCLOAK_ADMIN:admin}
    password: ${KEYCLOAK_ADMIN_PASSWORD:admin}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://eureka-server:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    com.netflix.eureka: WARN
    com.netflix.discovery: WARN
