apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: innovatech

resources:
  - namespace.yaml
  - config.yaml
  - postgres.yaml
  - keycloak.yaml
  - microservices.yaml
  - frontend.yaml
  - ingress.yaml
